version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:10"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:20"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/solver"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/produto-ui/prototipo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:40"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

